/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_packet_sniffer;


public class Main {
    public static void main(String[] args) {
        System.out.println("I am running!");
    }
}
