/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_packet_sniffer;


public class Main {
    public static void main(String[] args) {
        UserInterface ui = new UserInterface();
        ui.printWelcomeMessage();
        ui.doMainMenu();
    }
}
